### PR TITLE
added working logo/ banner for connect with me in github portfolio.

### PR DESCRIPTION
**Pull request by Rupesh-Darimisetti**
this allow your followers to connect to you than diverting to another external website

### CODE REVIEW

**Comment by Sajiyah-Salat** [comment]
Hello @Rupesh-Darimisetti Thank you for contributing Will review and merge this shortly

**Comment by Sajiyah-Salat** [comment]
I appreciate your input on my profile. Please explain to me how to add the same number of followers to the LinkedIn logo as you did to Twitter.

**Comment by Rupesh-Darimisetti** [comment]
> 

Sorry, i don't know in that icon widget there is no option like Twitter for LinkedIn

**Comment by Sajiyah-Salat** [comment]
Ohk

**Pull request merged**
